### PR TITLE
More tests!

### PR DESCRIPTION
**Pull request by gipert**
Maybe we should test also variable binned hists...

### CODE REVIEW

**Comment by gipert** [comment]
^ @oschulz can you approve GitHub actions for me?

**Comment by gipert** [comment]
Ha! how do we get around this?

https://docs.julialang.org/en/v1/base/base/#Base.hasproperty

**Comment by gipert** [comment]
@oschulz can you merge this, if it's ok for you?

**Comment by oschulz** [comment]
> can you approve GitHub actions for me

Sure - do you know what repo permissions are required for that?

**Comment by oschulz** [comment]
Thanks for this!

**Comment by giordano** [comment]
> do you know what repo permissions are required for that?

Now GitHub Actions don't run automatically for first-time contributors, every time they push to a pull request someone needs to click on the "approve" button.  I've been doing that the whole day :wink:

**Comment by oschulz** [comment]
> Now GitHub Actions don't run automatically for first-time contributors

Arggggh :-)

**Pull request merged**
